# Generated by Django 3.1.12 on 2025-01-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_history',
            field=models.JSONField(default=list),
        ),
    ]
